version: "3.7"
services:

    app-php-cli:
        env_file:
            - .env
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        tty: true
        stdin_open: true
        volumes:
            - .:/app